default['riak']['package']['version']['major'] = '2'
default['riak']['package']['version']['minor'] = '1'
default['riak']['package']['version']['incremental'] = '0'
default['riak']['package']['version']['build'] = '1'

default['riak']['config']['listener']['http']['internal']     = '0.0.0.0:8098'
default['riak']['config']['listener']['protobuf']['internal'] = '0.0.0.0:8087'
default['riak']['config']['storage_backend']                  = 'leveldb'
default['riak']['config']['riak_control.top_level']           = 'on'
default['riak']['config']['search.top_level']                 = 'on'
